from enum import Enum

class Categories(Enum):
    BEVERAGES: "BEVERAGES"
    FROZEN_FOODS: "FROZEN_FOODS"
    BAKERY: "BAKERY"
    DAIRY: "DAIRY"
    MEAT: "MEAT"
    PRODUCE: "PRODUCE"
    PAPER_GOODS: "PAPER_GOODS"
    PERSONAL_CARE: "PERSONAL_CARE"
    OTHER: "OTHER"